#!/usr/bin/env bash
# balancer install
sudo apt-get -y update
sudo apt-get install -y haproxy
echo "
frontend ken
    bind *:80
    mode http
    default_backend backendnodes
backend backendnodes
    balance roundrobin
    server 1894-web-01 34.198.248.145check
    server 1894-web-02 54.89.38.100   check " >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
